[Servidores]
devops-1 ansible_host=192.168.122.10
devops-2 ansible_host=192.168.122.11

; não funcionou
; devops-1 ansible_host=devops-1.local
; devops-2 ansible_host=devops-2.local
[Servidores:vars]
ansible_user=aluno